[build]
  base = "shopmi"
  publish = ".next" # Corrigido o caminho do diretório de publish
  command = "npm run build"
  # Omitir a verificação de segredos em diretórios de cache e build
  secrets_scan_omit_paths = [
    ".next/**/*",
    ".netlify/**/*"
  ]
  # Omitir a verificação da chave SHOPIFY_ADMIN_API_TOKEN
  secrets_scan_omit_keys = [
    "SHOPIFY_ADMIN_API_TOKEN"
  ]

[[plugins]]
package = "@netlify/plugin-nextjs"
